# Generated by Django 2.2.5 on 2019-09-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_TestCase',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('task_name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('script_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test_case',
            },
        ),
        migrations.CreateModel(
            name='Arguments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                (
                'task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Upload_TestCase')),
            ],
            options={
                'db_table': 'arguments',
                'unique_together': {('task_id', 'argument')},
            },
        ),
    ]
