# Generated by Django 2.2.5 on 2019-10-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arguments',
            name='default_value',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
