# Generated by Django 2.2.5 on 2019-10-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_arguments_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_testcase',
            name='description',
            field=models.TextField(),
        ),
    ]
