# Generated by Django 2.2.5 on 2019-10-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20191025_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_testcase',
            name='sample',
            field=models.CharField(default='', max_length=255),
        ),
    ]
