# Generated by Django 2.2.5 on 2019-11-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_upload_testcase_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_testcase',
            name='existed_attachment',
            field=models.BooleanField(default=False),
        ),
    ]
