# Generated by Django 2.2.5 on 2019-11-15 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_upload_testcase_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_testcase',
            name='existed_attachment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload_testcase',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
