# Generated by Django 2.2.5 on 2019-11-12 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_upload_testcase_existed_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_testcase',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
