# Generated by Django 2.2.5 on 2019-12-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20191115_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_testcase',
            name='modify_user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='upload_testcase',
            name='version',
            field=models.CharField(default='0.01', max_length=50),
        ),
    ]
