# Generated by Django 2.2.5 on 2019-10-20 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('upload', '0002_arguments_default_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('owner_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Project_task_argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('default_value', models.CharField(default='null', max_length=255)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Arguments')),
            ],
            options={
                'db_table': 'project_task_arguments',
            },
        ),
        migrations.CreateModel(
            name='Project_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Arguments')),
            ],
            options={
                'db_table': 'project_task',
            },
        ),
    ]
