# Generated by Django 2.2.5 on 2019-12-18 15:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Upload_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', unique=True)),
            ],
            options={
                'db_table': 'project_upload_time',
            },
        ),
    ]
