# Generated by Django 2.2.5 on 2019-11-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project_testscript_order',
            unique_together={('project_name', 'part_number', 'station_name')},
        ),
    ]
