# Generated by Django 2.2.5 on 2019-10-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191021_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_task_argument',
            name='description',
        ),
    ]
