# Generated by Django 2.2.5 on 2019-12-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_upload_time',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
