# Generated by Django 2.2.5 on 2019-10-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_task_argument_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_task',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Upload_TestCase'),
        ),
    ]
