# Generated by Django 2.2.5 on 2019-12-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191218_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_task',
            name='criteria',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='project_task',
            name='retry_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='project_task',
            name='timeout',
            field=models.IntegerField(default=10),
        ),
    ]
