# Generated by Django 2.2.5 on 2020-01-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20191230_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_task',
            name='interactive',
            field=models.CharField(default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='project_task',
            name='priority',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project_task',
            name='rule',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project_task',
            name='criteria',
            field=models.CharField(default='PASS', max_length=20),
        ),
    ]
