# Generated by Django 2.2.5 on 2020-02-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_upload_time_upload_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_upload_time',
            old_name='upload_message',
            new_name='allow_upload',
        ),
    ]
