# Generated by Django 2.2.5 on 2020-02-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200227_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_upload_time',
            name='id',
        ),
        migrations.AddField(
            model_name='project_upload_time',
            name='token',
            field=models.CharField(default='null', max_length=30, primary_key=True, serialize=False),
        ),
    ]
