# Generated by Django 2.2.5 on 2019-10-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20191021_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download_log',
            fields=[
                ('token', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'download_log',
            },
        ),
    ]
