# Generated by Django 2.2.5 on 2020-03-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_project_upload_time_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_upload_time',
            name='had_upload',
            field=models.BooleanField(default=False, max_length=255),
        ),
    ]
