# Generated by Django 2.2.5 on 2020-03-12 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_project_upload_time_had_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_upload_time',
            name='upload_user',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
