# Generated by Django 2.2.5 on 2019-10-25 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20191021_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
