# Generated by Django 2.2.5 on 2019-09-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('script_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('exec_time', models.IntegerField()),
                ('argument', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'up_testcase',
            },
        ),
    ]
