# Generated by Django 2.2.5 on 2019-09-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_testcase',
            name='script_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='upload_testcase',
            name='task_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
